apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: btran-dev-tls
spec:
  secretName: btran-dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: btran.dev
  dnsNames:
    - btran.dev
    - www.btran.dev
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
         - btran.dev
         - www.btran.dev